version: "3"
services:
  ext_mqtt_broker:
    image: eclipse-mosquitto
    ports:
      - "${EXT_MQTT_BROKER_PORT}:1883"

  int_mqtt_broker:
    image: eclipse-mosquitto
    ports:
      - "${INT_MQTT_BROKER_PORT}:1883"
      
  ext_mqtt_logger:
    image: afmm/mqtt_logger:1.0
    depends_on:
      - ext_mqtt_broker
    environment:
      - MQTT_BROKER_HOST=ext_mqtt_broker
      - MQTT_BROKER_PORT=1883
      - MQTT_LOGIN=${EXT_MQTT_LOGGER_LOGIN}
      - MQTT_PSWD=${EXT_MQTT_LOGGER_PSWD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PSWD=${DB_PSWD}
      - DB_NAME=${DB_NAME}
      - DB_LAST_VALUES_TABLE=${EXT_MQTT_BROKER_DB_LAST_VALUES_TABLE}
      - DB_HISTORY_TABLE=${EXT_MQTT_BROKER_DB_HISTORY_TABLE}
      
  int_mqtt_logger:
    image: afmm/mqtt_logger:1.0
    depends_on:
      - int_mqtt_broker
    environment:
      - MQTT_BROKER_HOST=int_mqtt_broker
      - MQTT_BROKER_PORT=1883
      - MQTT_LOGIN=${INT_MQTT_LOGGER_LOGIN}
      - MQTT_PSWD=${INT_MQTT_LOGGER_PSWD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PSWD=${DB_PSWD}
      - DB_NAME=${DB_NAME}
      - DB_LAST_VALUES_TABLE=${INT_MQTT_BROKER_DB_LAST_VALUES_TABLE}
      - DB_HISTORY_TABLE=${INT_MQTT_BROKER_DB_HISTORY_TABLE}

  iot_gateway:
    image: afmm/iot_gateway:1.0
    depends_on:
      - ext_mqtt_broker
      - int_mqtt_broker
    environment:
      - EMQTT_BROKER_HOST=ext_mqtt_broker
      - EMQTT_BROKER_PORT=1883
      - EMQTT_LOGIN=${IOT_GW_EMQTT_LOGIN}
      - EMQTT_PSWD=${IOT_GW_EMQTT_PSWD}
      - IMQTT_BROKER_HOST=int_mqtt_broker
      - IMQTT_BROKER_PORT=1883
      - IMQTT_LOGIN=${IOT_GW_IMQTT_LOGIN}
      - IMQTT_PSWD=${IOT_GW_IMQTT_PSWD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PSWD=${DB_PSWD}
      - DB_NAME=${DB_NAME}
      - DB_E2I_MAPPING_TABLE=${DB_IOT_GW_E2I_MAPPING_TABLE}
      - DB_I2E_MAPPING_TABLE=${DB_IOT_GW_I2E_MAPPING_TABLE}

  simple_web:
    image: afmm/simple_iot_control_panel:1.0
    ports:
      - "${SIMPLE_WEB_PORT}:80"
    environment:
      - WEB_SERVER_PORT=80
      - MQTT_BROKER_HOST=int_mqtt_broker
      - MQTT_BROKER_PORT=1883
      
  minecraft_iot:
    image: afmm/minecraft-iot:1.0
    ports:
      - "${MINECRAFT_SERVER_PORT}:25565"
    depends_on:
      - int_mqtt_broker
    environment:
      - MQTT_BROKER_HOST=int_mqtt_broker
      - MQTT_BROKER_PORT=1883

      
